
export const zkRow = {
    key: null,
    address: null,
    eth_balance: null,
    eth_tx_amount: null,
    zks2_balance: null,
    zks2_tx_amount: null,
    zks2_usdcBalance: null,
    zks1_balance: null,
    zks1_tx_amount: null,
    zks2_last_tx: null,
    dayActivity: null,
    weekActivity: null,
    monthActivity: null,
    l1Tol2Times: null,
    l1Tol2Amount: null,
    l2Tol1Times: null,
    l2Tol1Amount: null,
    contractActivity: null,
    totalFee: null,
    totalExchangeAmount: null,
};

export const snRow = {
    key: null,
    name: null,
    address: null,
    stark_eth_balance: null,
    stark_id: null,
    create_time: null,
    d_eth_amount: null,
    d_eth_count: null,
    d_usdc_amount: null,
    d_usdc_count: null,
    d_usdt_amount: null,
    d_usdt_count: null,
    d_dai_amount: null,
    d_dai_count: null,
    d_wbtc_amount: null,
    d_wbtc_count: null,
    w_eth_amount: null,
    w_eth_count: null,
    w_usdc_amount: null,
    w_usdc_count: null,
    w_usdt_amount: null,
    w_usdt_count: null,
    w_dai_amount: null,
    w_dai_count: null,
    w_wbtc_amount: null,
    w_wbtc_count: null,
    stark_tx_amount: null,
    stark_latest_tx: null,
    total_deposit_count: null,
    total_widthdraw_count: null
};