
export const zkRow = {
    key: null,
    address: null,
    eth_balance: null,
    eth_tx_amount: null,
    zks2_balance: null,
    zks2_tx_amount: null,
    zks2_usdcBalance: null,
    zks1_balance: null,
    zks1_tx_amount: null,
    zks2_last_tx: null,
    dayActivity: null,
    weekActivity: null,
    monthActivity: null,
    l1Tol2Times: null,
    l1Tol2Amount: null,
    l2Tol1Times: null,
    l2Tol1Amount: null,
    contractActivity: null,
    totalFee: null,
    totalExchangeAmount: null,
};